Remove-Item -Recurse -Path "C:\Users\Cole Mickens\AppData\Local\Google\Chrome\User Data"
Remove-Item -Recurse -Path "C:\Users\Cole Mickens\ansel"
Remove-Item -Recurse -Path "C:\Users\Cole Mickens\3D Objects"
Remove-Item -Recurse -Path "C:\Users\Cole Mickens\Videos"
Remove-Item -Recurse -Path "C:\Users\Cole Mickens\Favorites"
Remove-Item -Recurse -Path "C:\temp"