[commands.swipe.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""

[commands.swipe.four]
left_up = ""
right_up = ""
up = "/home/cole/.config/sway/menu-termite.sh"
left_down = ""
right_down = ""
down = ""
left = ""
right = ""
