#theme = "plain"
#theme = "solarized-dark"
#theme = "solarized-light"
#theme = "slick"
#theme = "modern"
#theme = "bad-wolf"
#theme = "gruvbox-light"
#theme = "gruvbox-dark"

theme = "plain"
icons = "none"

[[block]]
block = "music"
player = "spotify"
max_width = 36
buttons = ["play", "next"]

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "cpu"
frequency = true

[[block]]
block = "memory"
format_mem = "{Mup}%"

[[block]]
block = "battery"
#interval = 60
format = "{percentage}% {time} ({power})"

[[block]]
block = "time"
interval = 3
format = "%a-%_d %I:%M:%S "

