#!/bin/bash

github_username="colemickens"

repo_owner="$2"
repo_owner=${repo_owner#*:}
repo_owner=${repo_owner%%/*};

exec < /dev/tty

if [[ "${remote_repo}" != "${github_username}" ]]; then
	read -p "[pre-push hook] This repo is owned by ${repo_owner}. Proceed? (Y/n) " yn

	case $yn in
		[Yy] ) exit 0;;
		[Nn] ) exit 1;;
		* ) echo "Please answer y or n for yes or no.";;
	esac
fi
